version: '3.9'

services:
  server:
    build: .
    container_name: graphql-apollo-container
    env_file:
      - .env
    image: graphql-apollo-image
    restart: always
    ports:
      - $PORT:$PORT
